#!/usr/bin/env python3
"""
Example: Working with Time-Based CSV Exports
=============================================

This example demonstrates how to use the new time-aggregated CSV files
generated by the SLEAP analysis pipeline for efficient temporal analysis.

Author: Ikjot Sidhu
Date: May 2026
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

def analyze_temporal_patterns(output_dir="./analysis_results", node_name="bodycenter"):
    """
    Demonstrate analysis using time-aggregated CSV files.
    
    Parameters:
    -----------
    output_dir : str
        Directory containing the analysis results
    node_name : str
        Name of the tracked node (e.g., "bodycenter")
    """
    
    print("🔍 Analyzing temporal patterns using time-aggregated CSV files...")
    
    # File paths for different temporal resolutions
    frame_file = f"{output_dir}/{node_name}_inter_mouse_distances.csv"
    seconds_file = f"{output_dir}/{node_name}_inter_mouse_distances_by_seconds.csv"
    minutes_file = f"{output_dir}/{node_name}_inter_mouse_distances_by_minutes.csv"
    
    # Load data at different resolutions
    try:
        frame_data = pd.read_csv(frame_file)
        seconds_data = pd.read_csv(seconds_file)
        minutes_data = pd.read_csv(minutes_file)
        
        print(f"✅ Loaded data successfully!")
        print(f"   📊 Frame-level data: {len(frame_data)} rows")
        print(f"   ⏱️  Second-level data: {len(seconds_data)} rows")
        print(f"   ⏰ Minute-level data: {len(minutes_data)} rows")
        
    except FileNotFoundError as e:
        print(f"❌ Could not find data files. Please run the analysis pipeline first.")
        print(f"   Missing file: {e}")
        return
    
    # Example 1: Compare file sizes
    print("\n📁 File Size Comparison:")
    for file_path, label in [(frame_file, "Frame-by-frame"), 
                            (seconds_file, "Per-second"), 
                            (minutes_file, "Per-minute")]:
        if Path(file_path).exists():
            size_mb = Path(file_path).stat().st_size / 1024 / 1024
            print(f"   {label}: {size_mb:.2f} MB")
    
    # Example 2: Activity pattern analysis using second-level data
    print("\n🏃 Activity Pattern Analysis (using per-second data):")
    
    # Calculate activity periods (high vs low velocity)
    velocity_seconds_file = f"{output_dir}/{node_name}_velocities_by_seconds.csv"
    if Path(velocity_seconds_file).exists():
        velocity_data = pd.read_csv(velocity_seconds_file)
        
        # Calculate combined activity metric
        mouse1_activity = velocity_data['mouse1_velocity_pixels_per_second_mean']
        mouse2_activity = velocity_data['mouse2_velocity_pixels_per_second_mean']
        combined_activity = (mouse1_activity + mouse2_activity) / 2
        
        # Identify active vs inactive periods
        activity_threshold = combined_activity.median()
        active_periods = combined_activity > activity_threshold
        
        print(f"   🎯 Activity threshold: {activity_threshold:.1f} pixels/second")
        print(f"   ⚡ Active periods: {active_periods.sum()} seconds ({active_periods.mean()*100:.1f}%)")
        print(f"   💤 Inactive periods: {(~active_periods).sum()} seconds ({(~active_periods).mean()*100:.1f}%)")
    
    # Example 3: Social interaction analysis
    print("\n🤝 Social Interaction Analysis (using per-second data):")
    
    # Analyze proximity patterns
    mean_distance = seconds_data['inter_mouse_distance_pixels_mean']
    close_threshold = mean_distance.quantile(0.25)  # Bottom 25% = close interactions
    
    close_interactions = mean_distance < close_threshold
    print(f"   📏 Close interaction threshold: {close_threshold:.1f} pixels")
    print(f"   👥 Close interaction time: {close_interactions.sum()} seconds ({close_interactions.mean()*100:.1f}%)")
    
    # Find longest periods of close interaction
    close_periods = []
    current_period = 0
    for is_close in close_interactions:
        if is_close:
            current_period += 1
        else:
            if current_period > 0:
                close_periods.append(current_period)
            current_period = 0
    if current_period > 0:
        close_periods.append(current_period)
    
    if close_periods:
        print(f"   ⏱️  Longest close interaction: {max(close_periods)} seconds")
        print(f"   📊 Average close interaction duration: {np.mean(close_periods):.1f} seconds")
    
    # Example 4: Time-of-day analysis (if data spans multiple minutes)
    if len(minutes_data) > 1:
        print("\n🕐 Temporal Trends (using per-minute data):")
        
        # Create time bins
        minutes_data['time_bin'] = minutes_data['time_minutes'] // 5  # 5-minute bins
        
        # Calculate average distance per time bin
        time_trends = minutes_data.groupby('time_bin')['inter_mouse_distance_pixels_mean'].mean()
        
        print(f"   📈 Distance trends over 5-minute periods:")
        for time_bin, avg_distance in time_trends.items():
            start_min = time_bin * 5
            end_min = (time_bin + 1) * 5
            print(f"     Minutes {start_min:2d}-{end_min:2d}: {avg_distance:.1f} pixels average distance")

def demonstrate_data_efficiency():
    """Demonstrate the efficiency benefits of time-aggregated data."""
    
    print("\n⚡ Efficiency Demonstration:")
    print("=" * 50)
    
    # Simulated comparison
    frame_rate = 30  # fps
    recording_hours = 2
    
    frame_count = frame_rate * 60 * 60 * recording_hours  # Total frames
    second_count = 60 * 60 * recording_hours  # Total seconds
    minute_count = 60 * recording_hours  # Total minutes
    
    print(f"📹 Example: {recording_hours}-hour recording at {frame_rate} fps")
    print(f"   🎞️  Frame-by-frame data: {frame_count:,} rows")
    print(f"   ⏱️  Per-second data: {second_count:,} rows ({frame_count/second_count:.0f}x reduction)")
    print(f"   ⏰ Per-minute data: {minute_count:,} rows ({frame_count/minute_count:.0f}x reduction)")
    
    # Memory usage estimation (rough)
    columns_per_row = 8  # Approximate number of columns
    bytes_per_value = 8  # 64-bit float
    
    frame_memory_mb = (frame_count * columns_per_row * bytes_per_value) / 1024 / 1024
    second_memory_mb = (second_count * columns_per_row * bytes_per_value) / 1024 / 1024
    minute_memory_mb = (minute_count * columns_per_row * bytes_per_value) / 1024 / 1024
    
    print(f"\n💾 Estimated memory usage:")
    print(f"   🎞️  Frame-by-frame: {frame_memory_mb:.1f} MB")
    print(f"   ⏱️  Per-second: {second_memory_mb:.1f} MB")
    print(f"   ⏰ Per-minute: {minute_memory_mb:.1f} MB")

def main():
    """Main function to run all examples."""
    
    print("🐭 SLEAP Time-Based CSV Analysis Examples")
    print("=" * 50)
    
    # Check if analysis results exist
    output_dir = "./analysis_results"
    if not Path(output_dir).exists():
        print(f"❌ Analysis results directory '{output_dir}' not found.")
        print("   Please run the main analysis pipeline first:")
        print("   ")
        print("   from sleap_plotting import plotting_SLEAP")
        print("   plotting_SLEAP('your_data.h5', 'bodycenter', fps=30, output_dir='./analysis_results')")
        print("")
        demonstrate_data_efficiency()
        return
    
    # Run analysis examples
    analyze_temporal_patterns(output_dir)
    demonstrate_data_efficiency()
    
    print("\n✅ Example analysis complete!")
    print("\n💡 Key takeaways:")
    print("   • Use per-second data for behavioral analysis")
    print("   • Use per-minute data for long-term trends")
    print("   • Time-aggregated files are much smaller and faster to process")
    print("   • Pre-computed statistics save analysis time")

if __name__ == "__main__":
    main()
